trainer:
  max_steps: 40000
  val_check_interval: ~
  check_val_every_n_epoch: 1
  logger: ~
    # class_path: lightning.pytorch.loggers.wandb.WandbLogger
model:
  class_path: training.linear_semantic.LinearSemantic
  init_args:
    freeze_encoder: True
    network:
      class_path: models.histo_linear_decoder.LinearDecoder
      init_args:
        encoder_name: "hf-hub:MahmoodLab/UNI2-h"
        img_size: [448, 448]
    tiler:
      class_path: training.tiler.GridPadTiler
      init_args:
        tile: 448
        stride: 224           # overlap = 64
        weighted_blend: false # or true
        pad_mode: "reflect"   # optional; nice for images
        pad_value: 0.0
data:
  class_path: datasets.anorak.ANORAK
  init_args:
    overwrite_root: /home/valentin/workspaces/benchmark-vfm-ss/data/ANORAK
    img_size: [448, 448]
    prefetch_factor: 4
    num_workers: 0
